# 공통 설정
server:
  port: 8080
spring:
  application:
    name: api-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # 기본 활성 프로필을 dev로 지정
    group:
      "dev": "dev,local"
      "prod": "prod"
  datasource:
    hikari:
      maximum-pool-size: 5  # 최대 커넥션 수
      connection-timeout: 60000  # 커넥션을 얻기 위해 대기하는 시간: 60초
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never

# --- Service ---
chat:
  max-chat-person: 100
  max-chat-room: 30
  radius: 1.0 #km
  pre-create-day: 7 #7일전부터 생성 가능
  pre-view-day: 7 #7일전부터 축제보기 가능
  nickname-start: 3355

location:
  token:
    ttl-minutes: 15
  radius:
    limit: 1.0